### ISSUE TITLE
Academic request

### ISSUE THREAD

**Issue by liangxinyu0514** [smart-lty/REST#1]
Hello, I am reaching out to you as I have been attempting to replicate the code associated with your paper. However, I have encountered a persistent error that I have been unable to resolve. 
INFO:root:============================================
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 256
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 128
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 64
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 60
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 56
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 52
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 48
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 44
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 40
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 36
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 32
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 28
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 24
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 20
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 16
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 12
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 8
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 4
Random Seed:  42
INFO:root:Run Time Error! Reduce batch size. Current batch size: 0
Random Seed:  42
INFO:root:Run Time Error! CUDA Out of Memory!

       Despite adjusting the batch size and even trying the code on a GPU with 24GB of memory, the issue persists. I wanted to inquire whether you have encountered a similar error during your work on this project. Additionally, could you please provide details regarding the GPU and memory specifications you used for your experiments? This information would be immensely helpful in troubleshooting and resolving the issue.  
     Thank you!!!

**Comment by smart-lty** [comment]
Hello, this issue is caused by the try-exception block wihin the `train.py`, I think you can remove the try-exception block and rerun the code.

**Comment by smart-lty** [comment]
Hello, this issue is caused by the try-exception block wihin the `train.py`, I think you can remove the try-exception block and rerun the code.
